org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=stackedblocksfarmersdelight
mod_name=Stacked Blocks: Farmer's Delight
mod_license=MIT
mod_version=26.06.09-26.1-fabric
mod_authors=Axperty
mod_description=A mod that adds compatibility between Stacked Blocks and Farmer's Delight.
maven_group=com.axperty
archives_base_name=stackedblocksfarmersdelight

# Dependencies
fabric_api_version=0.144.3+26.1