org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=stackedblocksfarmersdelight
mod_name=Stacked Blocks: Farmer's Delight
mod_license=MIT
mod_version=26.06.24-26.2-fabric
mod_authors=Axperty
mod_description=A mod that adds compatibility between Stacked Blocks and Farmer's Delight.
maven_group=com.axperty
archives_base_name=stackedblocksfarmersdelight

# Dependencies
fabric_api_version=0.152.2+26.2